
name: Crystal CI

on:
  push:
  schedule:
      - cron: '0 0 * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        crystal: [latest, nightly]
        clang_version: [11, 12, 13, 14]

    runs-on: ubuntu-latest

    steps:
    - name: Download source
      uses: actions/checkout@v2
    - name: Install Crystal
      uses: oprypin/install-crystal@v1
      with:
          crystal: ${{ matrix.crystal }}
    - name: Install packages
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh ${{ matrix.clang_version }}
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
    - name: Build
      run: shards build
